AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  hw3photos_auto:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hw3photos_auto
  hw3lf2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: hw3lf2
      Handler: hw3lf2.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambda_functions
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::418888549033:role/service-role/lex-role-gsxpeog8'
      Environment:
        Variables:
          REGION: us-east-1
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /search
            Method: get
        putAZsAPI:
          Type: Api
          Properties:
            Path: /upload
            Method: put
  hw3lf1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: hw3lf1
      Handler: hw3lf1.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambda_functions
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::418888549033:role/service-role/lex-role-gsxpeog8'
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket:
              Ref: hw3photos_auto
            Events: s3:ObjectCreated:Put
      Environment:
        Variables:
          REGION: us-east-1